


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgtap" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."total_shares_stock_purchases_check"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$DECLARE
    total_value NUMERIC;
BEGIN
    SELECT SUM(amount_purchased) INTO total_value
    FROM "User_Stock_Purchases"
    WHERE user_id = NEW.user_id AND stock_id = NEW.stock_id;

    IF NEW.price_purchased <= 0 THEN
        RAISE EXCEPTION 'Price purchased must be greater than zero';
    END IF;

    IF NEW.amount_purchased = 0 THEN
        RAISE EXCEPTION 'Shares cannot buy or sell zero shares';
    END IF; 

    total_value := COALESCE(total_value, 0) + (NEW.amount_purchased);

    IF total_value < 0 THEN
        RAISE EXCEPTION 'Total shares for the stock cannot be less than zero';
    END IF;

    RETURN NEW;
END;$$;


ALTER FUNCTION "public"."total_shares_stock_purchases_check"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Account" (
    "first_name" character varying,
    "last_name" character varying,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "profile_picture" character varying
);


ALTER TABLE "public"."Account" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Stock_Info" (
    "stock_id" integer NOT NULL,
    "stock_close" double precision,
    "stock_volume" bigint,
    "stock_open" double precision,
    "stock_high" double precision,
    "stock_low" double precision,
    "sentiment_data" double precision,
    "time_stamp" "date" NOT NULL,
    "news_data" double precision
);


ALTER TABLE "public"."Stock_Info" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Stock_Predictions" (
    "stock_id" integer NOT NULL,
    "created_at" "date" NOT NULL,
    "model_1" "jsonb",
    "model_2" "jsonb",
    "model_3" "jsonb",
    "model_4" "jsonb",
    "model_5" "jsonb"
);


ALTER TABLE "public"."Stock_Predictions" OWNER TO "postgres";


ALTER TABLE "public"."Stock_Predictions" ALTER COLUMN "stock_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Stock_Predictions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Stocks" (
    "stock_id" integer NOT NULL,
    "stock_ticker" character varying,
    "stock_name" character varying,
    "search" "text"
);


ALTER TABLE "public"."Stocks" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."Stocks_stock_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."Stocks_stock_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."Stocks_stock_id_seq" OWNED BY "public"."Stocks"."stock_id";



CREATE TABLE IF NOT EXISTS "public"."Support" (
    "support_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "issue_type" "text" DEFAULT ''::"text" NOT NULL,
    "summary" "text" DEFAULT ''::"text" NOT NULL
);


ALTER TABLE "public"."Support" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."User_Feedback" (
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "content" "text" DEFAULT ''::"text" NOT NULL,
    "feedback_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL
);


ALTER TABLE "public"."User_Feedback" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."User_Stock_Purchases" (
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "date" timestamp with time zone NOT NULL,
    "price_purchased" double precision NOT NULL,
    "stock_id" integer NOT NULL,
    "amount_purchased" double precision NOT NULL
);


ALTER TABLE "public"."User_Stock_Purchases" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."User_Stocks" (
    "stock_id" integer NOT NULL,
    "shares_owned" double precision DEFAULT '0'::double precision NOT NULL,
    "desired_investiture" real NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "created_at" "date",
    CONSTRAINT "User_Stocks_desired_investiture_check" CHECK (("desired_investiture" > (0)::double precision))
);


ALTER TABLE "public"."User_Stocks" OWNER TO "postgres";


COMMENT ON COLUMN "public"."User_Stocks"."desired_investiture" IS 'how much do they want to invest';



ALTER TABLE "public"."User_Stocks" ALTER COLUMN "stock_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."User_Stocks_stock_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Stocks" ALTER COLUMN "stock_id" SET DEFAULT "nextval"('"public"."Stocks_stock_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."Account"
    ADD CONSTRAINT "Account_pkey" PRIMARY KEY ("user_id");



ALTER TABLE ONLY "public"."Stock_Info"
    ADD CONSTRAINT "Stock_Info_pkey" PRIMARY KEY ("stock_id", "time_stamp");



ALTER TABLE ONLY "public"."Stock_Predictions"
    ADD CONSTRAINT "Stock_Predictions_pkey" PRIMARY KEY ("stock_id", "created_at");



ALTER TABLE ONLY "public"."Stocks"
    ADD CONSTRAINT "Stocks_pkey" PRIMARY KEY ("stock_id");



ALTER TABLE ONLY "public"."Support"
    ADD CONSTRAINT "Support_pkey" PRIMARY KEY ("support_id");



ALTER TABLE ONLY "public"."User_Feedback"
    ADD CONSTRAINT "User_Feedback_pkey" PRIMARY KEY ("feedback_id");



ALTER TABLE ONLY "public"."User_Stock_Purchases"
    ADD CONSTRAINT "User_Stock_Purchases_pkey" PRIMARY KEY ("user_id", "date", "stock_id");



ALTER TABLE ONLY "public"."User_Stocks"
    ADD CONSTRAINT "User_Stocks_pkey" PRIMARY KEY ("stock_id", "user_id");



CREATE OR REPLACE TRIGGER "total_shares_stock_purchases_check_trigger" BEFORE INSERT OR UPDATE ON "public"."User_Stock_Purchases" FOR EACH ROW EXECUTE FUNCTION "public"."total_shares_stock_purchases_check"();



ALTER TABLE ONLY "public"."Account"
    ADD CONSTRAINT "Account_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Stock_Info"
    ADD CONSTRAINT "Stock_Info_stock_id_fkey" FOREIGN KEY ("stock_id") REFERENCES "public"."Stocks"("stock_id");



ALTER TABLE ONLY "public"."Stock_Predictions"
    ADD CONSTRAINT "Stock_Predictions_stock_id_fkey" FOREIGN KEY ("stock_id") REFERENCES "public"."Stocks"("stock_id");



ALTER TABLE ONLY "public"."User_Stock_Purchases"
    ADD CONSTRAINT "User_Stock_Purchases_stock_id_fkey" FOREIGN KEY ("stock_id") REFERENCES "public"."Stocks"("stock_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."User_Stock_Purchases"
    ADD CONSTRAINT "User_Stock_Purchases_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."User_Stocks"
    ADD CONSTRAINT "User_Stocks_stock_id_fkey" FOREIGN KEY ("stock_id") REFERENCES "public"."Stocks"("stock_id");



ALTER TABLE ONLY "public"."User_Stocks"
    ADD CONSTRAINT "User_Stocks_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE "public"."Account" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Enable read access for all users" ON "public"."Stock_Info" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."Stock_Predictions" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."Stocks" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Let users do anything they want with their own account" ON "public"."Account" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Let users do anything to their own stocks" ON "public"."Support" TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Let users do anything to their own stocks" ON "public"."User_Feedback" TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Let users do anything to their own stocks" ON "public"."User_Stocks" TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Let users do anything to their stocks" ON "public"."User_Stock_Purchases" TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."Stock_Info" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Stock_Predictions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Stocks" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Support" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."User_Feedback" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."User_Stock_Purchases" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."User_Stocks" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






GRANT ALL ON FUNCTION "public"."total_shares_stock_purchases_check"() TO "anon";
GRANT ALL ON FUNCTION "public"."total_shares_stock_purchases_check"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."total_shares_stock_purchases_check"() TO "service_role";







GRANT ALL ON TABLE "public"."Account" TO "anon";
GRANT ALL ON TABLE "public"."Account" TO "authenticated";
GRANT ALL ON TABLE "public"."Account" TO "service_role";



GRANT ALL ON TABLE "public"."Stock_Info" TO "anon";
GRANT ALL ON TABLE "public"."Stock_Info" TO "authenticated";
GRANT ALL ON TABLE "public"."Stock_Info" TO "service_role";



GRANT ALL ON TABLE "public"."Stock_Predictions" TO "anon";
GRANT ALL ON TABLE "public"."Stock_Predictions" TO "authenticated";
GRANT ALL ON TABLE "public"."Stock_Predictions" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Stock_Predictions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Stock_Predictions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Stock_Predictions_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Stocks" TO "anon";
GRANT ALL ON TABLE "public"."Stocks" TO "authenticated";
GRANT ALL ON TABLE "public"."Stocks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Stocks_stock_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Stocks_stock_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Stocks_stock_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Support" TO "anon";
GRANT ALL ON TABLE "public"."Support" TO "authenticated";
GRANT ALL ON TABLE "public"."Support" TO "service_role";



GRANT ALL ON TABLE "public"."User_Feedback" TO "anon";
GRANT ALL ON TABLE "public"."User_Feedback" TO "authenticated";
GRANT ALL ON TABLE "public"."User_Feedback" TO "service_role";



GRANT ALL ON TABLE "public"."User_Stock_Purchases" TO "anon";
GRANT ALL ON TABLE "public"."User_Stock_Purchases" TO "authenticated";
GRANT ALL ON TABLE "public"."User_Stock_Purchases" TO "service_role";



GRANT ALL ON TABLE "public"."User_Stocks" TO "anon";
GRANT ALL ON TABLE "public"."User_Stocks" TO "authenticated";
GRANT ALL ON TABLE "public"."User_Stocks" TO "service_role";



GRANT ALL ON SEQUENCE "public"."User_Stocks_stock_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."User_Stocks_stock_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."User_Stocks_stock_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
